### ISSUE TITLE
Setting preferences not working in 10.11 El Capitan

### ISSUE THREAD

**Issue by robbernabe** [amsysuk/public_scripts#2]
I've noticed that I can't set preferences via `defaults write` and have them persist in 10.11.  For example, setting the global preference for disabling "Shake mouse pointer to locate" I've found to be `defaults write -g CGDisableCursorLocationMagnification -bool TRUE`, but it seems my changes aren't saved (I've tried a logout and reboot, still no go). The research I've done thus far mentions the caching of preferences and `cfprefsd`, which lead me here to your repo.

Any ideas why these settings are not persisting?  Thanks!

**Comment by Daz-wallace** [comment]
Hi @robbernabe 
Sorry for the late reply.
I'm afraid that it is unlikely that `cfprefsd` is causing the issue as the `defaults` command works with preference caching, where as `plistbuddy` does not.

Sorry I can't be much more help!

Darren
