### ISSUE TITLE
Chrome browser version 58 breaks script

### ISSUE THREAD

**Issue by cornoir** [amsysuk/public_scripts#6]
FirstRun is created as well as the files but ChromeBrowser in Preferences says at the top:

"Chrome detected that some of your settings were corrupted by another program and reset them to their original defaults."

**Comment by Daz-wallace** [comment]
Thanks @cornoir
I'll take a look at this in the morning

**Comment by Daz-wallace** [comment]
Hi @cornoir 
I've not had the issue you describe (Corrupted settings) but I can verify that the Homepage setting doesn't seem to be working again with the latest release of Chrome (v58.0.3029.110).
Can you try grabbing a fresh version of the script and re-testing?

**Comment by Daz-wallace** [comment]
Scratch that, I can see what you mean within the settings screen.

I'll see what I can do, but it may be worth you looking into using this method instead [Chrome first run messages revisited – with added profiles](http://www.amsys.co.uk/2017/02/chrome-first-run-messages-revisited-added-profiles/)

**Comment by Daz-wallace** [comment]
Ok it looks like Google may have changed things a lot, enough to completely break the script :(
I'd suggest using the alternative solution as documented in the above blog as this won't be fixed anytime soon.
Sorry!

P.S. but open to pull requests to fix it!

**Comment by cornoir** [comment]
Will do.

Ed

Sent from my iPhone

On May 26, 2017, at 1:48 AM, Darren Wallace <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @cornoir<https://github.com/cornoir>
I've not had the issue you describe (Corrupted settings) but I can verify that the Homepage setting doesn't seem to be working again with the latest release of Chrome (v58.0.3029.110).
Can you try grabbing a fresh version of the script and re-testing?

**Comment by cornoir** [comment]
Looks like they added a lot of numbers (binaries?) to the Preference file when I tried to compare them.

I can configure some settings via a mobileconfig file, but need to write to the Preferences file things like do not track, etc that are only in the Preferences file, any suggestions on how to write those settings?

Something like defaults write I do not think will work.  Otherwise I will reverse engineer your python script to see what I can hack up to work.  Thanks for any help.


Ed


________________________________

**Comment by Daz-wallace** [comment]
Hey @cornoir 

The settings that are supported by profiles can be found [here](https://www.chromium.org/administrators/policy-list-3).

I recently used it in our Chrome profile (this morning actually) to skip the new 'Sign into your Google Account' Page.

If it's there, is a supported way to manage Chrome, otherwise its unsupported 😊

Hope that helps!

**Comment by Daz-wallace** [comment]
Closed as will not / cannot fix
